name: PHPStan

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    name: PHPStan - PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - uses: ramsey/composer-install@v3

      - run: composer validate --strict

      - run: composer analyse

      - run: composer test
